# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: "%env(APP_SECRET)%"
  trusted_proxies: "%env(TRUSTED_PROXIES)%"
  trusted_headers:
    [
      "x-forwarded-for",
      "x-forwarded-proto",
      "x-forwarded-host",
      "x-forwarded-port",
      "x-forwarded-prefix",
    ]

  # Note that the session will be started ONLY if you read or write from it.
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native
    cookie_lifetime: 604800 # 1 week

  #esi: true
  #fragments: true

  cache:
    pools:
      doctrine.second_level_cache_pool:
        adapter: cache.app

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
